---
# Playbook de Configuração de servidores AWS
# Configuração de WEBSERVERS =====================================
- name: Instalação e Configuração automática de WEBSERVERS
  hosts: tag_Name_webserver*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  vars:
    - http_port: 80
    - max_clients: 200
  tasks:
    - name: ensure apache is at the latest version
      yum: name=httpd state=latest
    - name: Configuring application
      copy: src=/root/demoinfra/webservers.log dest=/root/demoinfra/webservers.log
    - name: ensure apache is running
      service: name=httpd state=started enabled=yes
# notify:
#   - restart apache
# handlers:
#   - name: restart apache
#     service: name=httpd state=restarted
# ================================================================
# Configuração de APPSERVERS =====================================
- name: Instalação e Configuração automática de APPSERVERS
  hosts: tag_Name_appserver*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  vars:
    - http_port: 80
    - max_clients: 200
  tasks:
    - name: Install php latest version
      yum: name=php state=latest
    - name: Deploying application
      copy: src=/root/demoinfra/appservers.log dest=/root/demoinfra/appservers.log
# ================================================================
# Configuração de DBSERVERS =====================================
- name: Instalação e Configuração automática de DBSERVERS
  hosts: tag_Name_dbserver*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  vars:
    - http_port: 80
    - max_clients: 200
  tasks:
    - name: Installing DB server
      yum: list=sql
    - name: Configuring DBs
      copy: src=/root/demoinfra/webservers.log dest=/root/demoinfra/webservers.log
# ================================================================
# Configuração de Monitoração =====================================
- name: Adicionanto servidores na monitoração
  hosts: tag_Name_*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  tasks:
     - name: Adding servers to monitoring
       ping:
#    - name: Configuring DBs
#    copy: src=/root/demoinfra/webservers.log dest=/root/demoinfra/webservers.log
# ================================================================
...

