---
# Playbook de Configuração de servidores AWS
# Configuração de WEBSERVERS =====================================
- name: Instalacao e Configuracao automatica de WEBSERVERS
  hosts: tag_Name_webserver*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  vars:
    - http_port: 80
    - max_clients: 200
  tasks:
    - name: ensure apache is at the latest version
      yum: name=httpd state=present
    - name: Configuring application
      copy: src=webservers.log dest=/root/webservers.log owner=root group=root mode=0666
    - name: ensure apache is running
      service: name=httpd state=started enabled=yes
# notify:
#   - restart apache
# handlers:
#   - name: restart apache
#     service: name=httpd state=restarted
# ================================================================
# Configuração de APPSERVERS =====================================
- name: Instalacao e Configuracao automatica de APPSERVERS
  hosts: tag_Name_appserver*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  vars:
    - http_port: 80
    - max_clients: 200
  tasks:
    - name: Install php latest version
      yum: name=php state=present
    - name: Deploying application
      copy: src=appservers.log dest=/root/appservers.log owner=root group=root mode=0666
# ================================================================
# Configuração de DBSERVERS =====================================
- name: Instalacao e Configuracao automatica de DBSERVERS
  hosts: tag_Name_dbserver*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  vars:
    - http_port: 80
    - max_clients: 200
  tasks:
    - name: Installing DB server
      yum: list=sql
    - name: Configuring DBs
      copy: src=dbservers.log dest=/root/dbservers.log owner=root group=root mode=0666
# ================================================================
# Configuração de Monitoração =====================================
- name: Adicionanto servidores na monitoracao
  hosts: tag_Name_*
  remote_user: ec2-user
  become_method: sudo
  become_user: root
  tasks:
     - name: Adding servers to monitoring
       ping:
#    - name: Configuring DBs
#    copy: src=webservers.log dest=/root/webservers.log owner=root group=root mode=0666
# ================================================================
...

